server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bili?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update       # 开发阶段用 update，生产环境建议改为 validate 或 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# MyBatis 默认会自动扫描到 @Mapper，如果使用 XML Mapper，需指定 location
# mybatis:
#   mapper-locations: classpath:mapper/*.xml

# Spring Security、其他模块配置可按需补充

  redis:
    host: localhost
    port: 6380
    # 如果你的 Redis 配置了密码，就在这里加上：
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1

tianai:
  captcha:
    enabled: true
    type: SLIDER            # 可选：SLIDER / CLICK_WORDS / ARITHMETIC / TEXT
    storage:
      type: REDIS           # 存储类型，这里使用 Redis
    redis:
      prefix: "tiancap:"     # Redis 中的 key 前缀
      expire: 300           # 单位：秒
    width: 160              # 验证码图片宽度
    height: 60              # 验证码图片高度
    fontSize: 40            # 文字大小
    # 下面是可选项，如果想自定义背景图、文字颜色、干扰线等可以写在这里
    # background:
    #   colorFrom: "#FFFFFF"
    #   colorTo: "#FFFFFF"
    # text:
    #   charLength: 5

uid:
  workerId: 1
  biz-type: user
  segment:
    alloc: cached-segment
    step: 1000
    threshold: 20


mybatis:
  mapper-locations: classpath:/mapper/*.xml
