server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bili?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update       # 开发阶段用 update，生产环境建议改为 validate 或 none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# MyBatis 默认会自动扫描到 @Mapper，如果使用 XML Mapper，需指定 location
# mybatis:
#   mapper-locations: classpath:mapper/*.xml

# Spring Security、其他模块配置可按需补充
